### ISSUE TITLE
virgo:undeploy fails

### ISSUE THREAD

**Issue by albertattard** [frieder/virgo-maven-plugin#3]
I am not able to undeploy a module (using the virgo:undeploy maven command) which was deployed using the virgo:deploy maven goal.  Following is a complete stack trace:

C:\project>mvn virgo:undeploy
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.mycom.myproj 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- virgo-maven-plugin:1.0.1-SNAPSHOT:undeploy (default-cli) @ com.mycom.myproj ---
[info] Start undeploying the artefact from Eclipse Virgo
[info] Create new service URL: service:jmx:rmi://localhost:9875/jndi/rmi://localhost:9875/jmxrmi
[info] Create a new JMX connector (user = 'admin')
[info] Establish a connection to the defined MBean server
[info] Add bundle with symbolic name 'com.mycom.com.mycom.myproj' and version '3.0.0.SNAPSHOT' to the argument list
[info] Undeploy bundle
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.116s
[INFO] Finished at: Fri Mar 14 21:18:15 CET 2014
[INFO] Final Memory: 11M/464M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.flybyte.virgo:virgo-maven-plugin:1.0.1-SNAPSHOT:undeploy (default-cli) on project com.mycom.myproj: javax.management.Runt
imeMBeanException: java.lang.RuntimeException: org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Undeploy not possible as no properties with name com.mycom.com.mycom.myproj and version 3.0.0.SNAPSHOT is deployed
[ERROR] at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
[ERROR] at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
[ERROR] at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:821)
[ERROR] at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:791)
[ERROR] at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1486)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:96)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1327)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1426)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:847)
[ERROR] at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:601)
[ERROR] at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
[ERROR] at sun.rmi.transport.Transport$1.run(Transport.java:177)
[ERROR] at sun.rmi.transport.Transport$1.run(Transport.java:174)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
[ERROR] at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:553)
[ERROR] at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
[ERROR] at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
[ERROR] at java.lang.Thread.run(Thread.java:722)
[ERROR] at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:273)
[ERROR] at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:251)
[ERROR] at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:160)
[ERROR] at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
[ERROR] at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1017)
[ERROR] at net.flybyte.virgo.maven.deployer.Undeploy.execute(Undeploy.java:38)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:601)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR] Caused by: java.lang.RuntimeException: org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Undeploy not possible as no properties with name com.mycom.com.mycom.myproj and version 3.0.0.SNAPSHOT is deployed
[ERROR] at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doUndeploy(PipelinedApplicationDeployer.java:620)
[ERROR] at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.undeployInternal(PipelinedApplicationDeployer.java:600)
[ERROR] at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.undeploy(PipelinedApplicationDeployer.java:561)
[ERROR] at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.undeploy(PipelinedApplicationDeployer.java:545)
[ERROR] at org.eclipse.virgo.kernel.deployer.management.StandardDeployer.undeploy(StandardDeployer.java:60)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:601)
[ERROR] at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:192)
[ERROR] at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:174)
[ERROR] at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
[ERROR] at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
[ERROR] at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:235)
[ERROR] at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
[ERROR] at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:250)
[ERROR] at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
[ERROR] at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:791)
[ERROR] at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1486)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:96)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1327)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1426)
[ERROR] at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:847)
[ERROR] at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:601)
[ERROR] at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
[ERROR] at sun.rmi.transport.Transport$1.run(Transport.java:177)
[ERROR] at sun.rmi.transport.Transport$1.run(Transport.java:174)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
[ERROR] at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:553)
[ERROR] at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
[ERROR] at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
[ERROR] at java.lang.Thread.run(Thread.java:722)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

The project artifact id is: "com.mycom.myproj" and the group id is: "com.mycom".  I am using Virgo 3.6.2.

Any help is greatly appreciated.

**Comment by albertattard** [comment]
It was a configuration issue.

&lt;plugin&gt;
    &lt;groupId&gt;net.flybyte.virgo&lt;/groupId&gt;
    &lt;artifactId&gt;virgo-maven-plugin&lt;/artifactId&gt;
    &lt;version&gt;1.0.1-SNAPSHOT&lt;/version&gt;
    &lt;configuration&gt;
        &lt;symbolicName&gt;${project.artifactId}&lt;/symbolicName&gt;

The bundler used a different "symbolicName" to the undeployer.  Added the missing configuration and all worked.
